version = 1
[workspace]
root = "src/june-cek.mlb"

[language]
fixity-across-files = true

[language.successor-ml]
do-dec = true
opt-bar = true
or-pat = true
record-pun = true
record-update = true
vector = true
